spring:
  application:
    name: blog
    version: 1.0
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 230792AbV
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=TRUE
  jpa:
    hibernate.ddl-auto: "create-drop" # create-drop -TEMP
